Repository UnBArqDsw2024-1/2024.1_G5_My_AudioPodCast, pull requests merged in 2024-07, with the labels that each got.

#25 Feature/diagrama de classes
  docs/Modelagem/DiagramaClasses.md
  docs/_sidebar.md
  docs/images/diagramaClasse.png
Labels: documentation, modelagem

#35 Feat/creational design pattern
  .gitignore
  backend/README.md
  backend/app/builders/__init__.py
  backend/app/builders/admin_user_builder.py
  backend/app/builders/default_user_builder.py
  backend/app/builders/host_user_builder.py
  backend/app/builders/user_builder.py
  backend/app/database.py
  backend/app/enum/user_permission_enum.py
  backend/app/factories/__init__.py
  backend/app/factories/podcast_factory.py
  backend/app/models/__init__.py
  backend/app/models/category.py
  backend/app/models/episode.py
  backend/app/models/host.py
  backend/app/models/playlist.py
  backend/app/models/podcast.py
  backend/app/models/rating.py
  backend/app/models/user.py
  backend/app/test/__init__.py
  backend/app/test/test_user_builder.py
  backend/pytest.ini
  backend/requirements.txt
  docs/PadroesDeProjeto/3.1.GoFsCriacionais.md
  docs/images/esboco-builder.png
Labels: documentation, enhancement

#42 Inclusão da ata da reunião realizada no dia 25/07/2024.
  docs/Atas/21.07.2024.md
  docs/Atas/25.07.2024.md
  docs/_sidebar.md
Labels: documentation

#44 Revisao estrutural e comportamental
  docs/PadroesDeProjeto/3.2.1.GoFsEstruturaisDecorator.md
  docs/PadroesDeProjeto/3.3.GoFsComportamentais.md
  docs/PadroesDeProjeto/3.4.ParticipacoesPadroes.md
Labels: Revisão
